last hole working with conditional routes
whynotearth/we-are-mini-golf-frontend pull request #122
Opened 2021-01-23 04:40 UTC by freedannyv

No issue listed.
Issue completed.
I've added 3 conditionals that will determine the route of the last hole when it is clicked on.

Test: If the user selects a hole that isn't the last hole, route to new hole as normal.
Test: If there are other holes to play, the last hole warning will show up.
Test: If there are no other holes to play, the route will deliver the new-hole screen.

Bug fix: Added mode: new to the params when selecting "finish game anyway" from last-hole-warning page.

Refactor: now we loop through the players scores when clicking on last hole in the grid. That variable is passed on to the last-hole-warning page as a param, so it doesn't need to loop through again to get and output the "unplayed hole numbers".

2021-01-23 06:19 UTC, giteshk11 requested changes

2021-01-23 06:19 UTC, giteshk11 commented on src/views/LastHoleWarning.vue
> +            params: { holeNo: this.getPar.length, mode: 'new' }
is this always going to be new?

2021-01-23 06:19 UTC, giteshk11 commented on src/views/LastHoleWarning.vue
> +      let unfinishedHole = this.$route.params.unfinishedHoles;
if someone will refresh this page this data will be lost and error will come
we need to decouple this

2021-01-23 07:24 UTC, freedannyv commented on src/views/LastHoleWarning.vue
> +            params: { holeNo: this.getPar.length, mode: 'new' }
It needs to be a new hole for hole 14. It should always be new, yes

2021-01-23 07:29 UTC, freedannyv commented on src/views/LastHoleWarning.vue
> +      let unfinishedHole = this.$route.params.unfinishedHoles;
I won't be free again until Monday afternoon to update it

2021-01-26 03:29 UTC, paulchrisluke approved these changes

2021-01-26 16:32 UTC, giteshk11 commented on src/views/LastHoleWarning.vue
> +      let unfinishedHole = this.$route.params.unfinishedHoles;
i don't see fix for this

2021-01-28 01:15 UTC, freedannyv commented
@giteshk11 are you waiting for me to update something in this PR? I think that it is ready... I've left comments below your reviews also

2021-01-30 07:46 UTC, giteshk11 approved these changes

2021-01-31 03:59 UTC, merged