client issues updated for awards
whynotearth/we-are-mini-golf-frontend pull request #133
Opened 2021-01-28 05:28 UTC by freedannyv

#132 - added text center but don't know why client screen looks off center, all tests show it is centered already. Added white bg also.
#131 - as requested, the single review button is removed from page and added the review and new game buttons to show at all times.
#130 - font colours updated. Quote will show when other PR is merged, so no issue there.
#129 - done in another PR
#128 - every check completed, the major one being for only awards to pop up _if_ they are won. This works. Removed some data as requested, and added fade effect to text instead of bounce effect.

2021-01-28 05:47 UTC, paulchrisluke approved these changes

2021-01-28 07:25 UTC, freedannyv commented
#120 - centered text for Safari

2021-01-30 07:43 UTC, giteshk11 requested changes

2021-01-30 07:43 UTC, giteshk11 commented on src/views/Awards.vue
> +          this.award.img = require('../assets/ribbons/green-ribbon.png');
Check the size of these assets, these should be optimized else we can upload them on Cloudinary.

2021-01-30 07:43 UTC, giteshk11 commented on src/views/Awards.vue
> +      }
Don't really need this

2021-01-31 04:07 UTC, merged