rules menu updates
whynotearth/we-are-mini-golf-frontend pull request #158
Opened 2021-02-11 08:07 UTC by freedannyv

Updated closing button on rules screen (as per client req).
Updated rules background to grass img icon as per design.
Changed margin for par img to fit in box on NewHole.vue if player number is either == or > 1.
Updated a couple of quotes to read better English.
Changed NewHole background to better res image (as per client req).

2021-02-11 08:53 UTC, giteshk11 approved these changes

2021-02-11 08:55 UTC, giteshk11 requested changes
You havent removed BottomNavLayout.vue from generalRoutes.js

2021-02-11 09:35 UTC, freedannyv commented
> You havent removed BottomNavLayout.vue from generalRoutes.js

I didn't mean to remove the BottomNavLayout at all. How can we resurrect it?

2021-02-11 09:37 UTC, giteshk11 commented
Copy from staging and add that file again

2021-02-12 04:35 UTC, paulchrisluke approved these changes

2021-02-12 04:46 UTC, giteshk11 approved these changes

2021-02-12 04:46 UTC, merged