Client revs
whynotearth/we-are-mini-golf-frontend pull request #168
Opened 2021-02-17 07:53 UTC by freedannyv

Newer client revisions include:
- spinner on splash screen (functionality to set up with course load and precache - later)
- click outside of quote box in current-totals to close it
- placed error message above review modal (for iOS - needs testing)
- optimized background url from cloudinary for scores screen
- number **21** within presentation from client, updating splash screen styles:

https://docs.google.com/presentation/d/127ZjVDOK14uU-v9JiniHYrpfw6fs9_tUlS10LE1SraE/edit?fbclid=IwAR2rIDlTQG7Ev2Wmz4wC4gPAv3PJPQNAjcOLMKWTLF2m55dEz0fWF46zoUM#slide=id.gba68fafb4a_0_917

2021-02-17 07:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/whynotearth/we-are-mini-golf-frontend?pullRequest=168) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/whynotearth/we-are-mini-golf-frontend?pullRequest=168) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/whynotearth/we-are-mini-golf-frontend?pullRequest=168) it.</sub>

2021-02-17 08:22 UTC, giteshk11 requested changes

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +}
We don't need classes with the vendor prefix, it will be automatically handled.

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +@keyframes load5 {
Choose a better name for keyframes.

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +  font-size: 5px;
don't use `pixels` use `rem`, for font use `em`

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +  -ms-transform: translateZ(0);
remove vendor prefix

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +  height: 7px;
use `rem`

2021-02-17 08:22 UTC, giteshk11 commented on src/views/Splash.vue
> +  components: { BaseButton, Spinner },
you can change import statements to be lazy-loaded
e.g: 
```js
components: { BaseButton: () => import('@/components/utilities/BaseButton') },
```

2021-02-17 08:22 UTC, giteshk11 commented on src/components/Spinner.vue
> +export default {};
Give a name property here. Also, change the file name to `BaseSpinner.vue`.

2021-02-18 07:20 UTC, giteshk11 reviewed
Approved! Good work  @freedannyv 👍🏼

2021-02-18 07:21 UTC, giteshk11 approved these changes

2021-02-19 10:47 UTC, paulchrisluke commented
@giteshk11 @freedannyv is on family vacation from now into next week, can you take a look at this?

2021-02-19 11:06 UTC, merged