Down arrows
whynotearth/we-are-mini-golf-frontend pull request #214
Opened 2021-03-08 05:41 UTC by freedannyv

#191 
Added animated chevrons and removed 'detailed scores' button

2021-03-08 05:43 UTC, paulchrisluke approved these changes

2021-03-08 10:31 UTC, giteshk11 commented
@freedannyv can you pull staging and make changes to navbar again?

2021-03-08 13:50 UTC, giteshk11 requested changes

2021-03-08 13:50 UTC, giteshk11 commented on src/components/NavMenu.vue
> +    </component>
this is changed, please pull staging and make changes after that

2021-03-09 03:45 UTC, giteshk11 requested changes

2021-03-09 03:45 UTC, giteshk11 commented on src/components/NavMenu.vue
> +      "
umm why you have two click events here?

2021-03-09 03:59 UTC, giteshk11 approved these changes

2021-03-09 04:00 UTC, merged