Player object expanded
whynotearth/we-are-mini-golf-frontend pull request #57
Opened 2021-01-12 07:18 UTC by freedannyv

[ ] Bug Fix
[x ] Refactor
[ ] New Feature
[ ] Update to Existing Feature
[ ] Other (state below)

# Description

I've had to refactor all of the awards and results logic after adding the holeNo and par to the object when new scores are committed. This has made it easier for score calculation, and may speed up the app slightly?

2021-01-12 10:09 UTC, giteshk11 requested changes

2021-01-12 10:09 UTC, giteshk11 commented on src/views/CurrentTotal.vue
> +              }}
it would be better if you create a computed property of this

2021-01-13 03:01 UTC, freedannyv commented on src/views/CurrentTotal.vue
> +              }}
This is completed in new PR

2021-01-13 12:13 UTC, paulchrisluke approved these changes

2021-01-15 08:43 UTC, freedannyv commented
This is now redundant with the new holeScore array being implemented

2021-01-15 08:44 UTC, closed without merging